### ISSUE TITLE
Define gutter size based on column width

### ISSUE THREAD

**Issue by mjot** [gelobi/Griddify#27]
Hi,

I would like to achieve the following. I wan't a grid with 12 columns and 11 gutters between. I don't have any special document size. Is it possible to configure Griddify to create a grid with 12 columns and a gutter with the width of 1/4 of a column?

This would help so much for responsive designs. Thanks for your help!

**Comment by AriaMinaei** [comment]
Yeah, there is a beta version that works the way you described. See [this thread](https://github.com/gelobi/Griddify/issues/20). Download link is [here](https://github.com/pixana/griddify/releases/download/1.0.0-beta.4/Griddify-1.0.0-beta.4.zxp).
